[package]
authors = ["Jared Wolff <hello@jaredwolff.com>"]
description = "Board Support crate for the Circuitdojo Feather Tester"
documentation = "https://atsamd-rs.github.io/atsamd/atsamd21j16b/circuitdojo_tester/"
keywords = ["no-std", "arm", "cortex-m", "embedded-hal"]
license = "MIT OR Apache-2.0"
name = "circuitdojo_tester"
readme = "README.md"
repository = "https://github.com/atsamd-rs/atsamd"
version = "0.1.0"

[dependencies]
cortex-m = "~0.6"
cortex-m-semihosting = "~0.3.5"
embedded-hal = "~0.2.3"
nb = "~0.1"
panic-semihosting = "~0.5"

[dependencies.cortex-m-rt]
optional = true
version = "~0.6.12"

[dependencies.atsamd-hal]
default-features = false
path = "../atsamd/hal"
version = "~0.9"

[dev-dependencies]
panic-halt = "~0.2"

[features]
# ask the HAL to enable atsamd21j16b support
default = ["rt", "atsamd-hal/samd21j16b"]
rt = ["cortex-m-rt", "atsamd-hal/samd21j16b-rt"]
unproven = ["atsamd-hal/unproven"]
use_semihosting = []
